# Generated by Django 6.0.6 on 2026-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotels', '0003_phase3_upgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_hotels',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='hotels.hotel'),
        ),
    ]
